version: '3.8'

services:
  ms-script-dvr:
    build:
      context: contextPath
      dockerfile: Dockerfile
    container_name: dvr_server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node intelbras.js"
    expose:
      - "3000"
