services:
  ms-script-dvr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dvr_server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
